//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectKristal.VisualTests
{
    using Evergine.Common.Graphics;
    using Evergine.Framework.Graphics;
    using Evergine.Framework.Graphics.Effects;
    using Evergine.Mathematics;
    
    
    [Evergine.Framework.Graphics.MaterialDecoratorAttribute("3e01ffdf-efc4-49b2-a879-f4da876401a8")]
    public partial class MyComputeEffect : Evergine.Framework.Graphics.ComputeTaskDecorator
    {
        
        public MyComputeEffect(Evergine.Framework.Graphics.Effects.Effect effect) : 
                base(new ComputeTask(effect))
        {
        }
        
        public MyComputeEffect(Evergine.Framework.Graphics.ComputeTask computeTask) : 
                base(computeTask)
        {
        }
        
        public Evergine.Common.Graphics.Buffer Buffer0
        {
            get
            {
                return this.material.UABuffers[0].UABuffer;
            }
            set
            {
				this.material.SetUABuffer(value, 0);
            }
        }
    }
}
